#!/bin/bash
sudo apt install xorg \
	xfwm4 \
	lightdm \
	lightdm-gtk-greeter \
	xfce4-datetime-plugin \
	xfce4-genmon-plugin \
	xfce4-notifyd \
	xfce4-panel \
	xfce4-power-manager \
	xfce4-screenshooter \
	xfce4-session \
	xfce4-settings \
	xfce4-terminal \
	xfce4-whiskermenu-plugin \
	pipewire-audio \
	xfce4-pulseaudio-plugin \
	pavucontrol \
	policykit-1-gnome \
	menulibre \
	mugshot \
	wmctrl \
	xdotool \
	rofi \
	pcmanfm \
	gvfs-backends \
	gvfs-fuse \
	xarchiver \
	p7zip-full \
	catfish \
	network-manager \
	network-manager-gnome \
	vim-gtk3 \
	geany \
	lxappearance \
	arc-theme \
	breeze-cursor-theme \
	inxi \
	htop \
	neofetch \
	zenity \
	yad \
	fzf
